### PR TITLE
format the output-filename on template_gen.py

### PR DESCRIPTION
**Pull request by Halauwet**
Found an issue when construct template with option "plotdir" or "save_progress" on windows10, which can't use special character on the filename. So I added string format "strftime("%Y-%m-%dT%H%M%S")" for the default output-filename.

### What does this PR do?
Format output filename to fix conflict with special character on windows filename

### Why was it initiated?  Any relevant Issues?
https://github.com/eqcorrscan/EQcorrscan/issues/344

### PR Checklist
- [x] `develop` base branch selected?
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGES.md`.
- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Ace, thanks - you will need to fix the "stickler" issues before we can merge - which is just line length issues.  If you have a look at the "File Changed" tab you will see comments from stickler-ci regarding what you need to do.

**Comment by calum-chamberlain** [comment]
@Halauwet Can you add yourself to the contributors list please (see the list of things to do in the PR template that you filled out).  Can you also add a note in CHANGES.md pointing out that file naming has changed.

Otherwise this is good to go, thanks! :+1:

**Comment by Halauwet** [comment]
@calum-chamberlain  , I have updated the CHANGES.md and CONTRIBUTORS.md.
please check another commits on `plotting.py` it's another-same bug on plotting "cccsum"

**Comment by calum-chamberlain** [comment]
Please change those files in this PR, not in separate PRs.

**Pull request merged**
