### PR TITLE
Make CC-interpolation simpler & more robust

### PR DESCRIPTION
**Pull request by flixha**
### What does this PR do?
Replaces the CC-interpolation function that can be used for `lag_calc` and `catalog_to_dd` with a function that simply resamples the CC.

### Why was it initiated?  Any relevant Issues?

- CC-interpolation with `_xcorr_interp` "failed" (i.e., no improvement with interpolation) more often than maybe necessary. For the example data in the test, the new function fails to produce an improved CC with interpolation in only about 90 cases, while the previous one failed in about 150 cases. 
- `_xcorr_interp` had one specific weakness: it needs more than 2 samples with negative curvature to interpolate around the peak of the CC. If seismograms are filtered just below the Nyquist frequency (e.g., sampling rate 20 Hz and low-pass filter at 9.9 Hz) and contain plenty of high-frequency content just below the Nyquist frequency, then that criterion of more than 2 samples with negative curvature is often not fulfilled [(c.f. these lines)](https://github.com/eqcorrscan/EQcorrscan/blob/6286e4ff2dbb073eb98379ea69390ff3841b0b09/eqcorrscan/core/lag_calc.py#L74-L78) 
- On a dataset where the above was quite relevant, the new function improved the dt-accuracy for about 15 % more correlations than the old function (n=8*10^7)

### PR Checklist
- [X] `develop` base branch selected?
- [X] This PR is not directly related to an existing issue (which has no PR yet).
- [X] All tests still pass.
~- [ ] Any new features or fixed regressions are be covered via new tests.~
- [X] Any new or changed features have are fully documented.
- [X] Significant changes have been added to `CHANGES.md`.
~- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.~

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
This looks nice! Although I think this should go through a deprecation cycle - e.g. with an option to use the resampling method rather than the current method. I think the current method is documented in a couple of spots linking to a paper so we would need to find and change those as well.

**Comment by flixha** [comment]
@calum-chamberlain Of course, I'll fix this so that the old methods stays as the default with a deprecation message for a while, and users can choose this method. Should have mentioned: I saw that there was a [comment](https://github.com/eqcorrscan/EQcorrscan/blob/6286e4ff2dbb073eb98379ea69390ff3841b0b09/eqcorrscan/core/lag_calc.py#L67) in the function that you may have put in because you saw that it doesn't always work optimally - any more thoughts on that that we should consider for the new function?

**Comment by flixha** [comment]
I made the new function optional with `use_new_resamp_method=True` which is passed as `**kwargs`. The warning message is only shown once so that the log isn't completely spammed with this message - because this function is called many times when interpolation is turned on.

**Comment by flixha** [comment]
Tests now failing during installation, probably related to a breaking change in setuptools 61.0.0: https://github.com/pypa/setuptools/issues/3197 .. checking this now.

**Review by calum-chamberlain — APPROVED** [review]
Looks good to me - if we can get this in the next release then we can get the deprecation warning out of the way quickly.  If you are happy I will merge this.

**Comment by flixha** [comment]
Sounds good, thanks for merging!

**Pull request merged**
