### PR TITLE
Put legend inside of main frame

### PR DESCRIPTION
**Pull request by imankahbasi**
### What does this PR do?
Put legend inside of main frame Just for beauty.
### PR Checklist
- [ ] `develop` base branch selected?
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGES.md`.
- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Can you paste a plot of the new figure please.

**Comment by imankahbasi** [comment]
Before
20141011t001804700000z_20141011_001807700000

After
20141011t001804700000z_20141011_001807690000

**Comment by calum-chamberlain** [comment]
Does this still work well when many traces are plotted in a relatively small figure? Because the legend is now in the axis, does it get overlain by the other axes?

**Comment by imankahbasi** [comment]
I added correlation ratio to this plot too.
I will add this here very soon.

**Comment by calum-chamberlain** [comment]
I don't know what the "correlation ratio" is, but the cross-correlation values are given in the y-axis label (cc=...).

**Comment by imankahbasi** [comment]
> Does this still work well when many traces are plotted in a relatively small figure? Because the legend is now in the axis, does it get overlain by the other axes?

Yes, it get overlain by other axis. I increase alpha to make it clear.
2014-08-24T12_37_21 000000Z_template

**Comment by imankahbasi** [comment]
> I don't know what the "correlation ratio" is, but the cross-correlation values are given in the y-axis label (cc=...).

Yes, I meant cross-correlation values that show in y-axis.

**Comment by calum-chamberlain** [comment]
Is this done? You said
> I increase alpha to make it clear
have you done this and is this ready to merge?

**Comment by imankahbasi** [comment]
> have you done this and is this ready to merge?

Yes.
Alpha of legend add hear
`axes[0].legend(lines, labels, loc='upper right', framealpha=1)`

**Pull request merged**
