### PR TITLE
fix cccsum_plot

### PR DESCRIPTION
**Pull request by imankahbasi**
### What does this PR do?
It fix some issue in _match_filter_plot.
### Why was it initiated?  Any relevant Issues?
#339 
### PR Checklist
- [x] `develop` base branch selected?
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGES.md`.
- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Thanks for this @imankahbasi - can you add a remade plot from #339 as a comment here showing the new figure please, just so we have it for reference in the future.

Closes #339 

It looks like the appveyor fails are unrelated - I will try and fix the test-runners this week on develop, then re-run the tests here before merging if that's okay?

**Comment by imankahbasi** [comment]
> Thanks for this @imankahbasi - can you add a remade plot from #339 as a comment here showing the new figure please, just so we have it for reference in the future.

Of course, I will add new plot tomorrow from institute's PC.

> It looks like the appveyor fails are unrelated - I will try and fix the test-runners this week on develop, then re-run the tests here before merging if that's okay?

Of course, It's good. :)

**Comment by imankahbasi** [comment]
Remade plot from #339 

Template name; Detection time (UTC); Number of channels; Channel list; Detection value; Threshold; Threshold type; Input threshold; Detection type
20140916t22_53_11400000z0; 2014-09-16T22:53:17.740000Z; 2; [('DLRN', 'SN'), ('DLRN', 'SZ')]; 1.999999761581421; 1.478461742401123; MAD; 10; corr
cccsum_plot_20140916t22_53_11400000z0_2014-09-16T00_00_00 000000Z

**Comment by calum-chamberlain** [comment]
Great, thanks @imankahbasi!

**Pull request merged**
