### PR TITLE
Shorten and clarify a warning message

### PR DESCRIPTION
**Pull request by dr-glenn**
### PR Checklist
- [x] `develop` base branch selected?
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [ ] Significant changes have been added to `CHANGES.md`.
- [x] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Hi @dr-glenn - thanks for this - it looks like you made your changes on the wrong branch. Was the only change that you meant to make the changes to multi_corr.c? If so I can make those changes to develop in a new PR (or you could)?

**Comment by dr-glenn** [comment]
I would appreciate it if you would put that one change into the correct
branch - I have too many ways to do this wrong.
At sometime I was advised to submit changes to develop branch. But I
probably cloned from master. I've never collaborated on any Git hosted
project before, so it was easy to mess it up! Was I supposed to clone from
develop?

I would like to understand the meaning of the countless cccsum messages and
perhaps make them more helpful.
I am very puzzled that the cccsum error messages appear as INFO messages!
Here is the code in lag_calc.py:
                msg = ('lag-calc has decreased cccsum from %f to %f - '
                       % (detection.detect_val, checksum))
                Logger.error(msg)
In my output the message is labeled as "INFO". How does that happen?

BTW, my neighbor is a developer/manager at Github and I asked for his help.
To my lament that git was perplexing, he said that no one truly understands
it. Kind of like quantum mechanics. Oh great.
----
Glenn Nelson in Santa Cruz

**Comment by dr-glenn** [comment]
BTW, I am working with Susan Schwartz at UCSC. Got my Ph.D. in 1991, but
then went into Silicon Valley software development. Retired now, so I've
returned to a better place.
----
Glenn Nelson in Santa Cruz

**Comment by calum-chamberlain** [comment]
Hi Glenn, thanks I will close this PR and open a new one with that change based on develop. 

when you clone, you clone the whole repository (all of the branches), and you should either have checked out develop and made changes there, then made a pull request to develop, OR made changes on master and made a pull request to master. The way EQcorrscan does its branching is to maintain master as a current-version branch, and all changes are made to develop then merged to master before a new release (apart from documentation changes which are made directly to master so that the docs get updated immediately). Apologies, it isn't a great model! Nor is it well described.

Error messages (`Logger.error`) should never appear as `INFO` type. Are you sure that line is the source of your `INFO` messages?

**Comment by dr-glenn** [comment]
I see many messages like this:
2022-03-14 12:57:35,549 - __main__ - INFO: lag-calc has decreased cccsum
from 0.668884 to 0.379192 -

I wanted to know where they came from and perhaps understand what they
meant. I am sure that it comes from lag_calc.py, vicinity of line 326.
----
Glenn Nelson in Santa Cruz

**Comment by dr-glenn** [comment]
Calum, I have another question and I don't see myself making a pull request
until I know more.
Templates have some strange name restrictions. For example here is one of
mine:
2019_03_23t23_10_12.tgz
The only special character allowed is underscore! And only lower case
letters are allowed! Why on earth (or deep within it) are these limitations
made? I wanted to use underscore and hyphen and capital 'T'. (I also
discovered that using colon in a filename was very bad when I copied the
file to Windows). I don't think the same restrictions are imposed on
match_filter and lag_calc output files

BTW, I name my detection plots like
this: Templ-2019-07-30T07-22-09_Det-2018-05-12T08-49-09.png. Very useful. I
have programs that catalog the detections based on the image filenames.
----
Glenn Nelson in Santa Cruz

**Comment by calum-chamberlain** [comment]
I'm not sure what is going on with that INFO message - the format of the messages should be that the Logger is named after the file that generates to log message. Your logger appears to be called `__main__` which I wouldn't have expected.

RE template naming - the regular expression: `^[-a-z_0-9]+$` is checked against, which allows lower-case letters, numbers and `_` and `-` characters. This is done to ensure portability of termplates across operating systems when written into Tribes. Windows doesn't allow `:`s, and is (generally) case insensitive. You should be able to use the hyphen character. You should however be able to write to whatever filename you want.

**Comment by calum-chamberlain** [comment]
I wonder if the StreamtoLogger is picking up messages that should and converting them to INFO. Can you try running without capturing sydout and stderr?

Anyway, the messages mean that running lag-calc has resulted in worse correlations than you had without running lag-calc, which generally shouldn't happen. If you are getting lots of these messages then something has probably gone wrong somewhere and we might need to dig in to why. For that I would suggest opening a new issue.

**Comment by dr-glenn** [comment]
An answer, but still a puzzle.
I turned off these:
    # Output stdout and stderr to logger
    sys.stdout = StreamToLogger(logger, logging.INFO)
    sys.stderr = StreamToLogger(logger, logging.INFO)
Indeed, the messages no longer appear as INFO messages, and they only
appear in the stdout/stderr file named run.log. That is, I run my program
this way:
python my_detect.py >& run.log&
Logging generates both a console and file output in my main program. The
Logger output from lag_calc now only appears on the console, but it is not
from the consoleHandler that I declared in my program my_detect.py. Of
course not! And I never set a formatter for the root logger, so lag_calc
only outputs a message with no module and no level information, like this:
lag-calc has decreased cccsum from 0.654930 to 0.290600 -
Strange, I thought that the default formatter was more informative.
I should have started with this:

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s
%(message)s',
                    datefmt='%m-%d %H:%M',
                    )

Colum, thank you so much for all the time you've spent reading my emails
and educating me. Now I'll leave you in peace and try to understand more
about lag_cal and those messages.

Oh, one more question. The detection plots are very nice, but I wish I
could dynamically recreate them so that I could zoom in. Would also like to
make the template overlay partially transparent. I know how to do all this
on my own, but are there core or util classes or functions that can do the
job?

----
Glenn Nelson in Santa Cruz

**Comment by calum-chamberlain** [comment]
Hey Glenn,

All the plotting that is done in EQcorrscan (I think) is handled by functions in eqcorrscan.utils.plotting - you might be able to find what you need there?

C

**Pull request closed without merging**
