### PR TITLE
patch subspace docs

### PR DESCRIPTION
**Pull request by cjhopp**
Docs build fine locally after adding h5py to MOCK_MODULES.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Not a clue why everything failed there - unfortunately I haven't got readthedocs set up to build PRs, so we will have to wait until this merges into develop to check that the docs actually work.

It built fine locally for me, but I had h5py and script all there...  did yours *not* build without mocking h5py?

**Comment by cjhopp** [comment]
Welp, I can't recreate the issue locally it turns out. They still build fine without mocking h5py, so maybe that commit is irrelevant...

**Comment by cjhopp** [comment]
Tried removing h5py but still building okay. No ImportError though so my environment is probably a bit screwy.

**Comment by calum-chamberlain** [comment]
Sounds like it - maybe make a fresh conda env with limited dependencies. and install eqcorrscan in there without installing dips (use the --force option it looks like).

**Comment by cjhopp** [comment]
Conda not finding obspy for py35 and 36 on Linux.

Failure of mag_calc.calc_max_curv on all platforms.

**Comment by cjhopp** [comment]
Also, I'm able to recreate the failing subspace docs in a dedicated, clean conda env with no h5py mock and no h5py install.

**Comment by calum-chamberlain** [comment]
That failure is very strange... Perhaps IRIS updated their catalog? Will look into it.

RE ObsPy: did you add the condo-forge channel - they are all [there](https://anaconda.org/conda-forge/obspy/files).

It might be something I have done to the docs - utils.correlate isn't showing either, possibly a build issue... I'll have a play.

**Comment by calum-chamberlain** [comment]
@cjhopp I made some changes - mocked out the `utils.libutils` submodule and it appears to work, can you cast your eye over my changes and the docs which are built [here](http://eqcorrscan.readthedocs.io/en/cjhopp-sub_doc-patch/submodules/core.subspace.Detector.html) - make sure you select the docs for this branch in the bottom left.

If they look okay, we will ignore the failing test (which is unrelated, and I will work on that in another PR) we could merge?

**Comment by cjhopp** [comment]
Docs and changes look fine to me. Merging.

P.S. I wasn't sure how to view doc builds for branches other than 'latest', 'stable', etc... on readthedocs. Is it a config file change on out end or was that feature always available and I just missed it?

**Comment by calum-chamberlain** [comment]
The options for different versions of the docs are always in the bottom left, there is usually just a stable, develop and latest build, but I added this one temporarily.
To add other branches, you can go into the settings on readthedocs and add builds.

**Pull request merged**
