### PR TITLE
reversed template generation for match_filter

### PR DESCRIPTION
**Pull request by xiansch**
added reversed template gen capability to match filter.
check me on this, it's my first pull request! Woooo

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Far out, this is exciting!
Have you run the tests on your local database @xiansch ? Looks like appveyor failed on `eqcorrscan/tutorial.py`. which is strange - I might try rebasing as this file isn't about in the current eqcorrscan.
I will review your changes once we have things working. :) Thanks for this!

**Comment by cjhopp** [comment]
+1 Englishman typing 'Far out'.

**Comment by calum-chamberlain** [comment]
@xiansch I think you will need to rebase your branch - do you know how to do that, or have you done that already?

**Comment by calum-chamberlain** [comment]
@xiansch I think you will need to rebase your branch - do you know how to do that, or have you done that already?

**Comment by calum-chamberlain** [comment]
So this was a mess - I'm going to close this PR and open a new one, based on the current develop branch, with the changes to match_filter that add in reversed template thresholding.

**Pull request closed without merging**
