### PR TITLE
Float cc threshold

### PR DESCRIPTION
**Pull request by imankahbasi**
### What does this PR do?
Float threshold  to phase-picking in lag_calc. Make it flexible phase picking.
### Why was it initiated?  Any relevant Issues?
 #371
### PR Checklist
- [x] `develop` base branch selected?
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests still pass.
- [ ] Any new features or fixed regressions are be covered via new tests.
- [ ] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGES.md`.
- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by imankahbasi** [comment]
I'm trying to write better notes and warning. I add them in an commit.
First of all, I would like to now it's okay or not?
Can you help me how can I write test part for this new lines?

**Comment by calum-chamberlain** [comment]
Thanks for this - I think the best way to start would be to make a jupyter notebook example of this usage, with some plots of what this does. We can include that in the docs and point to that from the doc-string to help make it clear what `float_cc` does (I'm still not clear on what it does). That should also help us work out how to test this.

**Comment by calum-chamberlain** [comment]
@imankahbasi - did you still want to work on this, or shall we close this PR?

**Comment by imankahbasi** [comment]
> @imankahbasi - did you still want to work on this, or shall we close this PR?

Hello, dear Chamberlain.
I'm so sorry for my long time absence.
Actually I'm interested in working on this PR, but I got envolved in many projects that take all of my time.
Unfortunately, Closing this PR maybe is a choice. :(

**Comment by calum-chamberlain** [comment]
No worries on taking a while and doing other things! I will close this for now and we can come back to it when you have time.

**Comment by flixha** [comment]
@imankahbasi I don't remember seeing the details of this PR when you opened the issue unfortunately. Just wanted to note that I implemented a similar functionality to allow lower lag-calc correlations to set a pick with the option `min_cc_from_mean_cc_factor`. See: https://github.com/eqcorrscan/EQcorrscan/blob/d3f2e97c6c6c3f2b371cb6619458c808b138b0ec/eqcorrscan/core/lag_calc.py#L211-L215)

A value of `min_cc_from_mean_cc_factor=1.0` will allow picks to be set when the trace correlation is equal or better compared to the average of the detection. So the formulation is a bit different compared to your percentage, but conceptually it should be possible to directly translate those values in case you want to use the feature.

**Comment by imankahbasi** [comment]
Thank you @flixha .
Maybe this option is something that I would like to use.
I will see and explore on it as soon as I can.

**Pull request closed without merging**
