### PR TITLE
Remove unnecessary condition from Template.__init__

### PR DESCRIPTION
**Pull request by cjhopp**
Also a minor fix to clustering.dist_mat_km.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Looks like the fails might be a connection issue, can you rerun them?

**Comment by cjhopp** [comment]
Travis login/github account integration is smooth...Appveyor not so much? I can't get it to give me a re-run button on the builds...still working on it.

**Comment by cjhopp** [comment]
Alright. I guess I'm a bit confused with the setup process for Appveyor. Am I supposed to have access to rebuild permissions if I just login to Appveyor with my github login? Once I click the 'details' button next to the failed build, I only get the option to download the log.

**Comment by calum-chamberlain** [comment]
You should do if you link with your github account and this organisation...

Otherwise I can do it?

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by cjhopp** [comment]
I'll keep looking into it. It wasn't an issue to link with my/the organisation account on Travis, though. Also, Travis builds have failed thrice now. All with a 'build stalled' sort of behavior. I'll try again before I leave today.

**Comment by calum-chamberlain** [comment]
The osx builds often stall, they are a lot slower than the Linux builds. You can rebuild individual runs rather than the whole job if that is the case. Of just ignore them. Tbh if they work on Linux and Windows chances are they will work on osx

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by cjhopp** [comment]
Cool with me. Although no passes on any platform.

But I only changed two lines...

**Comment by cjhopp** [comment]
I'm going to go ahead and merge this guy. Cool?

**Pull request merged**
