### PR TITLE
Plotting features

### PR DESCRIPTION
**Pull request by cjhopp**
Adds ability to plot detection rate in cumulative_detections (wrapped by Party.plot and Family.plot) as well as specify a date range and a minimum number of detections. Makes the plots more useful when searching through large number of templates over large periods of data.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Looks like appveyor is playing silly buggers, but otherwise this one should be passing all tests after merge of #175 to sort out circleci's random change to failing.

Do you have any examples of the new plotting/updated docs? Do we need to build the docs for this and check they all work before we merge?

**Comment by calum-chamberlain** [comment]
So we can ignore the codecov patch fail because we haven't written tests for plotting thus far :disappointed: 
I'm building the docs [here](http://eqcorrscan.readthedocs.io/en/cjhopp-plotting-feats/).

**Comment by calum-chamberlain** [comment]
@cjhopp where are we with this - did you check the docs generated and include some plotting examples?

**Comment by cjhopp** [comment]
We areeeeee.......at exactly the same place we were a month ago. Standby for updated docs/examples.

**Comment by cjhopp** [comment]
Alright, @calum-chamberlain . Everything but codecov passes. Lemme know what you think about the examples. Also, do the docs build [here](http://eqcorrscan.readthedocs.io/en/cjhopp-plotting-feats/submodules/autogen/eqcorrscan.utils.plotting.cumulative_detections.html) (for example) automatically? Or is that something I have to trigger on my end?

**Comment by calum-chamberlain** [comment]
Yup, they built automagically, looks like they had no issues on the last build.  Can you put pointers to the docs examples that have changed? Then I will have a check of them and review.
And yup, looks good, shame we still don't test plotting, and something I really want to get going, but not going to happen this year methinks.

**Comment by calum-chamberlain** [comment]
[This](https://pypi.python.org/pypi/pytest-mpl) looks like what we want!

**Comment by cjhopp** [comment]
That does indeed!

Only docs changes should be [here](http://eqcorrscan.readthedocs.io/en/cjhopp-plotting-feats/submodules/core.match_filter.Party.html) and in plotting [here](http://eqcorrscan.readthedocs.io/en/cjhopp-plotting-feats/submodules/autogen/eqcorrscan.utils.plotting.cumulative_detections.html#eqcorrscan.utils.plotting.cumulative_detections)

However, not all of the functions show up in the Party API docs, which was the case before this PR, I think.

**Comment by calum-chamberlain** [comment]
Ah, what are we missing in Party?

**Comment by calum-chamberlain** [comment]
Also, is there anyway to specify bin-size with rate plotting?

**Comment by cjhopp** [comment]
At the moment, it's dynamic based on the size of the date range. Should be simple enough to allow that to be user defined, though.

Quite a few Party functions missing...the ones I changed/added were filter and plot, neither or which appear.

**Comment by calum-chamberlain** [comment]
Can you add them in? Should just have to add them in to `eqcorrscan/doc/submodules/eqcorrscan.core.match_filter.Party.rst` - add both to the `.. autosummary::` list and add an `.. auto method::` statement for each.

**Comment by calum-chamberlain** [comment]
P.S. dynamic is good. 👍

**Comment by calum-chamberlain** [comment]
Looks like somethings gone wrong with this one: http://eqcorrscan.readthedocs.io/en/cjhopp-plotting-feats/submodules/core.match_filter.Party.html#eqcorrscan.core.match_filter.Party.plot

**Comment by calum-chamberlain** [comment]
I think the circleci fail should be fixed in develop now, so updating just to check - its obviously not something you have done.  
Will merge this morning.
Fanks! 👍

**Pull request merged**
