### PR TITLE
 Add 'metric' argument to Party.decluster()

### PR DESCRIPTION
**Pull request by cjhopp**
By default, `Party.decluster()` should now consider the average single-station correlation value. Raw correlation sum can be specified with the `metric` argument.

### CODE REVIEW

**Comment by cjhopp** [comment]
I think fails are timeouts due to LOOONNNGG subspace tests in time domain. AppVeyor builds passing and subspace tests much faster with eventual pull #92 so this is probably good to go?

**Comment by calum-chamberlain** [comment]
What are we waiting on for #92? It would be good to merge that before this to make sure that all things pass…

**Comment by cjhopp** [comment]
I was just waiting for a review. But I'll merge #92 if you're down.

**Comment by calum-chamberlain** [comment]
Shall review #92 in the next hour (yay jetlag).

**Comment by cjhopp** [comment]
Surely can! I'll add it at home while watching Peaky Blinders.

**Comment by cjhopp** [comment]
Aight, there's a shot at it. Not sure if that's an acceptable way to do it? Test are still a bit obscure to me.

**Comment by cjhopp** [comment]
A real potpourri of failures, but they seem to be ones we've seen before (i.e. weird numpy error for 3.5 on Linux and GeoNet client issues)

**Comment by calum-chamberlain** [comment]
Travis looks good, but why the appveyor fail? Their mobile site crashes my phone with that long test log, any ideas?

**Comment by cjhopp** [comment]
```
================================== FAILURES ===================================
______________ [doctest] eqcorrscan.utils.archive_read.read_data ______________
044 
045     .. note:: A note on arc_types, if arc_type is day_vols, then this will         look for directories labelled in the IRIS DMC conventions of         Yyyyy/Rjjj.01/... where yyyy is the year and jjj is the julian day.         Data within these files directories should be stored as day-long,         single-channel files.  This is not implemented in the fasted way         possible to allow for a more general situation.  If you require more         speed you will need to re-write this.
046 
047     .. rubric:: Example
048 
049     >>> from eqcorrscan.utils.archive_read import read_data
050     >>> from obspy import UTCDateTime
051     >>> t1 = UTCDateTime(2012, 3, 26)
052     >>> stachans = [('FOZ', 'HHZ'), ('JCZ', 'HHZ')]
053     >>> st = read_data('GEONET', 'FDSN', t1, stachans)
UNEXPECTED EXCEPTION: ValueError(u'The current client does not have a station service.',)
```

**Comment by calum-chamberlain** [comment]
Just rerun?

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by cjhopp** [comment]
Still having permissions issues with AppVeyor. I can rerun builds for successful tests, but not for failed ones. I only see the 'Log' button for failed tests. Looking into it now.

**Comment by calum-chamberlain** [comment]
That's annoying, I wonder if there is something I need to do.
Anyway, have restarted that build. Should green light, then go for it.

**Comment by cjhopp** [comment]
Okeedoke. Merging now.

With small changes like this, just a couple of missed lines means missing the codecov target. Am I understanding that right? I did add some additional coverage for test_party_decluster(), but not quite enough.

**Pull request merged**
