### PR TITLE
implement #454

### PR DESCRIPTION
**Pull request by d-chambers**
# What does this PR do?
Adds the ability to generate templates from any ol' object with a a get_waveforms method. This is useful for using EQCorrScan with ObsPlus.

# Why was it initiated? Any relevant Issues?
#454

### PR Checklist
- [x] `develop` base branch selected?
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGES.md`.
- [x] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by d-chambers** [comment]
Ok @calum-chamberlain,

This is probably a 7/8-baked solution. Feel free to push any changes or let me know what you would like changed and I will do it.

Thanks!

**Review by calum-chamberlain — APPROVED** [review]
Looks like how I would have done it.

**Comment by calum-chamberlain** [comment]
Looks good to me - did you check that it works with an ObsPlus WaveBank? If so then I will go ahead and merge. The fails are still NCEDC FDSN timeouts.

Thanks!

**Comment by d-chambers** [comment]
Ya, it does work with ObsPlus

**Pull request merged**
