### PR TITLE
threeD_seismplot developed

### PR DESCRIPTION
**Pull request by imankahbasi**
### What does this PR do?
Plot seismicity and stations in a 3D, movable, zoom able space with support of inventory, catalog and locations with maximum of two groups of seismicity now and all inputs are optional.
### PR Checklist
- [x] `develop` base branch selected?
- [x] This PR is not directly related to an existing issue (which has no PR yet).
- [x] All tests still pass.
- [x] Any new features or fixed regressions are be covered via new tests.
- [x] Any new or changed features have are fully documented.
- [x] Significant changes have been added to `CHANGES.md`.
- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
As in the other PR, changing the function names and arguments is best avoided. What was the goal of this PR?

**Comment by calum-chamberlain** [comment]
Closing due to lack of response.

**Comment by imankahbasi** [comment]
>Closing due to lack of response.

Hi, I apologize for not responding.
I have been so busy for an important exam and working on my thesis.
It will long for nearly another month.
I will begin again as soon as I can.

**Comment by calum-chamberlain** [comment]
All good - just reopen when you are ready.

**Pull request closed without merging**
