### PR TITLE
Merge working subspace branch

### PR DESCRIPTION
**Pull request by cjhopp**
Subspace tests passing, haven't checked the others locally yet.

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
All the travis tests look like they stem from changing the U and V matrices to the correct way - could you fix the tests so they reflect this change?

**Comment by cjhopp** [comment]
Updating now. Already working on the assorted svd-related changes.

**Comment by calum-chamberlain** [comment]
Couple more test issue in the clustering test and plotting dockets from the argument change.

I'm unsure why lag-calc is failing and this isn't related. I will try and fix this upstream.

**Comment by cjhopp** [comment]
Well, those were silly.

**Comment by cjhopp** [comment]
Facepalm

**Pull request merged**
