### PR TITLE
WIP: Findpeaks optimisation

### PR DESCRIPTION
**Pull request by calum-chamberlain**
Not ready to merge yet, work in progress.

So far we have changed decluster to a more efficient NumPy implementation (thanks to @d-chambers), and compared to a c-implementation of decluster.  Speeds were similar, but we will go with the Python for simplicity and maintainability.

Still to do:
- [x] test for looping;
- [x] serial looping over multiple cccsum arrays;
- [x] parallel looping over multiple cccsum arrays;
~~- [ ] benchmarks.~~

This is work on the request in #159

### CODE REVIEW

**Comment by calum-chamberlain** [comment]
Okay, so I have implemented a parallel loop and this is now called from matched-filter, which should speed things up a bit overall.

I also put the compiled version back in because testing the current decluster gave slower results than expected (about 10x slower than compiled). When I did that and tested them against one another, for the test dataset they both give the same results, but for a noisy randomised dataset they gave different results.  On closer inspection I saw that the compiled version was taking peaks happily, but the Python version missed some and took smaller adjacent peaks.  I will try and work up a test and put it up here.

**Comment by d-chambers** [comment]
If the C version is more correct and much faster we can just use that; EQcorrscan already has C code that needs to be compiled so one more function doesn't really add a great deal of complexity right?

So do you need help adding tests that prove correctness, or do you still want to look at some benchmarking? If the C function is that much faster, and the python version is not even correct anyway, it may not be worth trying to fix the python version or coming up with benchmarks.

Nice use of the pool boy :wink:

**Comment by calum-chamberlain** [comment]
Note, I may just be feeding the decluster function the wrong things. - @d-chambers do you want to gave a go at making it work? Otherwise I can tomorrow?

**Comment by calum-chamberlain** [comment]
Fair enough - I'm fairly sure the C is correct, and reasonably fast. It is really simple C-code, doesn't require any weird libraries and doesn't care about system (ASFAIK), so yup, the C might be worth just going with rather than expending more effort.

Also, couldn't help myself with pool_boy, one of my new favourite bits of EQcorrscan. :small_airplane: 

I also moved `time_func` into utils.timer because I think it will be useful for more than just correlate.

I will just:
- [ ] go with the C version
- [ ] make a test or two more to test correctness
- [ ] add a more thorough test for finding all-peaks (I have left this option in, because I feel like I might want it for something else at some point)
- [ ] Document the limitation of find-peaks for closely spaced peaks that do not drop below the threshold between them.

I think that should do it for this one. @yifanyin is this the kind of thing you were expecting? After we merge this into develop we can create an experimental branch off develop for individual channel thresholding if you would like?

**Comment by calum-chamberlain** [comment]
In saying that I think it is correct, now not so sure with the circleci fail for declustering detections.  Will check.

**Comment by calum-chamberlain** [comment]
Just needed to use longs rather than ints for trig_int.

**Comment by d-chambers** [comment]
I am having issues with my ubuntu machine (wont boot, black screen) this may take awhile to sort out. Will try to write some more tests when it is back up.

**Comment by calum-chamberlain** [comment]
Oh no!

Looks like I have somehow introduced a memory leak in this latest one, so I would avoid running it until I fix that otherwise it will crash your machine again.

**Comment by calum-chamberlain** [comment]
Looks like the memory leak doesn't happen on my laptop... curious.

**Comment by yifanyin** [comment]
These codes are getting so advanced I can hardly keep up and find all the nobs I can turn ;)
I now tested eqcorrscan 0.2.7 on my machine and it works fine. However, on a 32-core machine, the multiprocess seems to freeze up and won't go into _find_peaks. Still trying to sort it out why. I'll try to test the new _find_peaks if someone can direct me to the right version!

**Comment by calum-chamberlain** [comment]
@yifanyin, that sounds like it freezes in the cross correlations? If so, what are you setting for the xcorr_func, concurrency and cores arguments?

**Comment by yifanyin** [comment]
@calum-chamberlain My setting: xcorr_func=None, concurrency="multiprocess", cores=30. Now I see where are the option of the xcorr_func haha. I'll also try alter them.

**Comment by calum-chamberlain** [comment]
Try using concurrent as the concurrency argument. It will use the openmp parallel loop, which should be faster than multiprocess. Neither should use more cores than you have channels though, so if you have less than 30 channels I would recommend just sticking the cores argument to be the number of channels.

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by calum-chamberlain** [comment]
Try using concurrent as the concurrency argument. It will use the openmp parallel loop, which should be faster than multiprocess. Neither should use more cores than you have channels though, so if you have less than 30 channels I would recommend just sticking the cores argument to be the number of channels.

**Although**: _pool_boy should take care of limiting the cores to be a maximum of the number of traces, so that argument shouldn't be an issue - you may just have to run shorter chunks of data if your memory is filling...?

**Comment by d-chambers** [comment]
I re-factored the tests a bit to make it more modular and easier to add new test cases to TestPeakFindSpeeds. Let me know what you think. 

Would it be worthwhile to also allow for a concurrency option? Not sure how a thread pool would compare to a process pool. The tests are seg faulting after pulling the latest changes to the C routine so I can't really test it atm.

**Comment by calum-chamberlain** [comment]
I shall see if I can reproduce and work out that segfault. 
I don't think a multi thread would be with it, but you are welcome to try if you want to?

**Comment by d-chambers** [comment]
ok, I just needed to recompile, segfault is gone my bad

**Comment by calum-chamberlain** [comment]
Those tests look good, took a couple of looks to get my head around the requests thing, but seems good to me.

~~I can't immediately reproduce the seg-fault, have you recompiled?~~

Above comment, seet, I think that would have been due to the change from ints to floats - I was having to use longs rather than straight ints for large gaps between things, but, in this version, the intervals between peaks are normalised by trig_int, which results in smaller gaps (smaller numbers to store in memory).  The main reason for doing this is because longs are not consistent between 32-Bit and 64-Bit machines, but Python always passes longs as int64 (on 32-Bit machines, long is int32...), so on 32-Bit machine, passing an array of longs doesn't work so well. This seemed like the simplest way around that.  It does slow down the Python part a bit, because an array of ints is converted to floats and divided by trig_int.

**Comment by calum-chamberlain** [comment]
Okay, so, do we want to add more tests for correctitude (Friday words), or are we happy with this as is? And do you want to try a threading option?

Not sure why stickler hasn't run, but glad that all others are passing. I have tested install on all my machine (windows 32Bit, Ubuntu 64-Bit and OSX 64-Bit), but haven't tested on larger machines, but `pool_boy` should take care of CPU allocations so that it doesn't go crazy, so I think I'm happy on that front.

Also, I should think about using `pool_boy` for other multiprocessing things in EQcorrscan...

**Comment by d-chambers** [comment]
I think it is good, we can add more tests as bugs crop up

**Comment by calum-chamberlain** [comment]
Sweet, appveyor is confusing me. I'll fix those and be merge tomorrow.

I'm not planning on doing another release until 0.3.0 now so this won't make it out into the wild for a bit. Unless bugs are raised in the current release...

**Pull request merged**
